language: node_js
node_js:
- 5.2.0
before_install:
- npm install
script:
- webpack
sudo: false
before_deploy:
- npm-prepublish --verbose
deploy:
- provider: npm
  email: "$NPM_EMAIL"
  api_key: "$NPM_API_KEY"
  on:
    tags: true
env:
  global:
  # NPM_EMAIL
  - secure: "wPRD06tJaUXswBwh7VqdUX/BGT5rmTtGSNx4z8uaGGw7vtrrR9m/T7VsUFKKFLurqPIOFxm/5TDjCU0/jDRGbSw4dLq31EBI5nnJDIZWqYmDoc7we+UaEbGMOlfbQosKlXM5pcBHPIrkwTRdrpvXPDez0Q/1CoQGzlAatyyOvbg0xucm3+rB8p9GNvJPeHRuMOe8mYLUX60Ec9pcadfD6kKO/Ognv4bJESqkJZCca1phreV5YuhdIO2H9XYuGVtdtQNztLCxux7H6CqkutnwRUTZpGzTT0aiRQOt8zjcRLrIEzsaTrythdFmLzIc44aWw+FqyLi0J7VIeDv+D69NOltlxVfS2VorCaOSyS+isCf4iYzcQkze8dISUyw0PSAt8FZS3WDuOd8mil9hz6SDMUo6QdotHk9sh40lvK0BKUZ5RItiRcTJddQU021DgfxZpEw0lkLeOWYwcB4dKHwK15kCxWY0owHU2KYjm7lVPIKWgSE72XVVRB3Zd+Ra/DvUQDdv6xQrA+sOjnChLT/xt9s+FTaXI0rts9l7oyJKTbPix8uwy41NToq2nUH4v6z2CsWafqBvHGRa3p4oLLhjG9XiiWg+mY3Xcp8c24IQiPsILu4XQWsCS6m4ny+Eirpl8BzDlSFm4Qv/acBoiNaZ8lLEqH+p2H0VaWbGjbfrthg="
  # NPM_API_KEY
  - secure: "aSqKFuCGx8BMOxoayu4HTB8rHpWp3AOj8ZnPYNZxRf14Gjgdv/QarKdCubs2fE1zn/jH7sMxLd2x2KJS5l8Tu6BG8kfiiNBX40eBUlUbHiPLqDikXvtllwezRXZD7L1TT4dmwW2q3+XnVr7KAUGmJKfh4k4/GL78TGsaehXs5pqjumMHhXbatn/oOvHcKpKM5iDK+oI95lNdm2zCm9HKRWNNkzpjsglUCim3KvvqCYh+dA6qGT4que2d4+ppGSttmKFdpgdJ6lVJ07VmLM+N8/tY0VDoC4itL2jx+wMKk57hVMX0ryTAxVjqqIBDaBNqyHZ606Foj1I/o+DvaqB5Dl+Evqizd6w3FCHf7Tq+tJTqV48c6et8tD6x3WBXjzdZ9Nxxyd/a1pF9Vj1IqU8GGOs3yKVVMbLZKhQcxQWi137N+f+0OuisDRO2rJzOtKiLoHMIvh8d8s9Zd60D7gZ4p9WX6eToGZLL+vtEzdMVi3Mn0MADkXS+PgVuC+66tYAsJlFnYTnxjq2pYrQ8ojCGo5gxSi8Y6AQiaFcuzB8OZSPsU4ZpyoMRl88z//A82xtgRQ5M3ZCgwNpgaSyVMOjTUPKxwgoZbDdyqkaXo7QpNZbfixIKtKW4LEe+NtKTxQK3iVGRSaF3vQLSM5Lp0t+wvxSL/xkur/+h0/ssIT9U93k="